
function D_FlipFlop_config(this_block)

  % Revision History:
  %
  %   21-Sep-2015  (12:03 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\02_Nand_2_Tetris\00_Working_Files\KeyBoard_Unit\KB_Vr_5_Corrcting\D_FlipFlop.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('D_FlipFlop');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('D');
  this_block.addSimulinkInport('Clk');
  this_block.addSimulinkInport('En');

  this_block.addSimulinkOutport('Q');

  Q_port = this_block.port('Q');
  Q_port.setType('UFix_1_0');
  Q_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('D').width ~= 1);
      this_block.setError('Input data type for port "D" must have width=1.');
    end

    this_block.port('D').useHDLVector(false);

    if (this_block.port('Clk').width ~= 1);
      this_block.setError('Input data type for port "Clk" must have width=1.');
    end

    this_block.port('Clk').useHDLVector(false);

    if (this_block.port('En').width ~= 1);
      this_block.setError('Input data type for port "En" must have width=1.');
    end

    this_block.port('En').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('D_FlipFlop.vhd');

return;


